
-- Punto 1

SELECT descripcion, id_solicitud , ID_CLIENTE  
FROM (select descripcion, id_solicitud , ID_CLIENTE 
from  T01_SOLICITUD
INNER JOIN T00_ESTADO
ON  T01_SOLICITUD.estado = T00_ESTADO.id_estado 
WHERE ESTADO = 1 
AND FECHA_INGRESO BETWEEN '01/01/2000' AND '31/01/2000')
INNER JOIN T02_CLIENTE
ON T01_SOLICITUD.ID_CLIENTE = T02_CLIENTE.ID_CLIENTE
WHERE  FECHA_NACIMENTO EQUALS '01/01/1990';

--Punto 2

CREATE FUNTION NUMBER_REQUESTS (ID_CLIENTE)

BEGIN
   SELECT COUNT(ID_SOLICITUD) FROM T01_SOLICITUD
   WHERE ID_CLIENTE = ID_CLIENTE;
END;

--Punto 3

CREATE TABLE T01_SOLICITUD
( ID_SOLICITUD NUMBER PRIMARY KEY,
  ESTADO NUMBER,
  FECHA_INGRESO DATE,
  MONTO FLOAT,
  ID_CLIENTE VARCHAR(100)
);

--Punto 4

CREATE INDEX INDEXSOLICITUD ON T01_SOLICITUD (ID_SOLICITUD);

--
